### ISSUE TITLE
DNSCrypt logo in SVG

### ISSUE THREAD

**Issue by yegortimoshenko** [DNSCrypt/dnscrypt-website#2] opened 2018-06-15 16:06 UTC
Hi, is there a SVG version of DNSCrypt logo? I would like it for nylira/prism-break#2003.

**Comment by publicarray** [comment] 2018-06-17 10:38
Hi @yegortimoshenko, 
I am a fan of prism break project.
As far as I'm aware there is no SVG version of the logo available. However It is possible that @jedisct1 might know more.

**Comment by publicarray** [comment] 2018-06-23 12:37
Duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/523

**Closed by publicarray** 2018-06-23 12:38 UTC
